spring:
  profiles:
    active: local
  config:
    import:
      - application-naver-client.yml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # 주의
    properties:
      hibernate:
        format_sql: true
springdoc:
  version: '1.0.0'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true
server:
  forward-headers-strategy: framework